#!/bin/bash

cd /home/fabric/test/fab/fabric/fabric-samples/test-network

./network.sh down

./network.sh createChannel -c mychannel -s couchdb -ca ########## Adding the first 2 orgs into the channel ##########

cd addOrg3/

./addOrg3.sh up -c mychannel -s couchdb -ca

## Check if the ca_org3 is in the fabric_test network
# docker network inspect fabric_test 
docker network connect fabric_test ca_org3 ## if not

# deploy the chaincode for the 2 ORGS 
./network.sh deployCC -ccn custom -ccp ../pdm-custom/chaincode-javascript -ccl javascript -c mychannel

cd ../
#Changing to ORG3
export PATH=${PWD}/../bin:$PATH
export FABRIC_CFG_PATH=$PWD/../config/
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_LOCALMSPID=Org3MSP
export CORE_PEER_TLS_ROOTCERT_FILE=${PWD}/organizations/peerOrganizations/org3.example.com/peers/peer0.org3.example.com/tls/ca.crt
export CORE_PEER_MSPCONFIGPATH=${PWD}/organizations/peerOrganizations/org3.example.com/users/Admin@org3.example.com/msp
export CORE_PEER_ADDRESS=localhost:11051

#Package the chaincode nad install it in org3 
peer lifecycle chaincode package custom.tar.gz --path ../pdm-custom/chaincode-javascript --lang node --label custom_1.0.1
peer lifecycle chaincode install custom.tar.gz
#peer lifecycle chaincode queryinstalled

output=$(peer lifecycle chaincode queryinstalled)

# Extract the package ID using grep and cut
package_id=$(echo "$output" | grep -o 'Package ID: [^,]*' | cut -d' ' -f3)

# Export the package ID as an environment variable
export CC_PACKAGE_ID="$package_id"

# Print the extracted package ID
echo "Exported CC_PACKAGE_ID: $CC_PACKAGE_ID"

# export CC_PACKAGE_ID=custom_1.0.1:15ad23ae09277e7d5a9f833ee791fa0a1a778488159e54314bc9ed100798cf0e
peer lifecycle chaincode approveformyorg -o localhost:7050 --ordererTLSHostnameOverride orderer.example.com --tls --cafile ${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem --channelID mychannel --name custom --version 1.0.1 --package-id $CC_PACKAGE_ID --sequence 1

#checking everything is ok
peer lifecycle chaincode querycommitted --channelID mychannel --name custom